### ISSUE TITLE
38ESR builds fail to open https sites with new NSS

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/nss-os2#2]
After upgrading to the version of NSS in exp, and also with my own experimenting, Firefox 38esr as distributed with AOS as well as the corresponding version of SeaMonkey silently fail to load secure sites that are not cached. Thunderbird also fails to make secure connections to the email server.
Google is a good test site here, attempting to load leaves a blank page and blank URL.

**Comment by SilvanScherrer** [comment]
I dont use esr 38 anymore. I wonder what this could be. Please try to debug it. As i have unfortunately no time to Play with older ffox.

**Comment by dryeo** [comment]
It's likely a protocol mismatch of some type. I'll look into it but not very hopeful.
One workaround may be to package the working NSPR/NSS dlls and have people install them in their program directory as well as pointing out that it is an old unsupported browser. This should work fine as usually people are using run! to set BEGINLIBPATH and LIBPATHSTRICT.

**Comment by dryeo** [comment]
Building a new SM linked against NSS 3.47 and then running it against NSS 3.23 has the same results, which I expected. Note that most HTTPS sites do open, Google does not which is more evidence that some sites are using a newer cipher and won't fall back for some reason.
I'll see if I can build a debug version of FF38

**Comment by SilvanScherrer** [comment]
did you debug that further why mozilla fails? As w/o this info I will close this ticket. As I can't find any evidence thats something is broken in nss so far.

**Comment by dryeo** [comment]
No. Attempts to build a debug version of 38ESR were unsuccessful and 
there's just no information as sites just silently fail to load at all. 
It seems to be tls 1.3 that is failing. Interestingly, Niel updated his 
blondeguy site and 45.9ESR started failing the same way. Unluckily we 
couldn't figure out why.
Simplest might be to advise people who want to run 38esr to copy the 
known good NSPR and NSS DLLs into their program directory.

**Comment by SilvanScherrer** [comment]
Ok so i close it as not fixable
