### ISSUE TITLE
Upgrading to NSS 3.47.0-1 breaks linking xul.dll

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/nss-os2#3]
After upgrading NSS, attempting to build any Mozilla app dies at
```
145:29.25 weakld: cannot open library file '/@unixroot/usr/lib_s.a'.
145:29.25 emxomfld: weak prelinker failed. (rc=8)
145:29.26 make.EXE[5]: *** [xul.dll] Error 1
```
This seems to be due to a change in @unixroot/usr/bin/nss-config. Comparing the output to current and previous nss-config --libs shows this (NSS 3.47.0 installed in O: )
```
K:\usr\bin>sh nss-config --libs
-L/@unixroot/usr/lib -lssl3 -lsmime3 -lnss3 -lnssutil3

O:\usr\bin>sh nss-config --libs
/@unixroot/usr/lib -L/@unixroot/usr/lib -lssl3 -lsmime3 -lnss3 -lnssutil3
```
and patching the new nss-config to remove a variable and make it more equivalent to the older nss-config fixes the build.
```
--- nss-config.rpm      2019-12-02 19:56:24.000000000 -0800
+++ nss-config  2019-12-03 07:40:48.000000000 -0800
@@ -127,7 +127,7 @@
 fi

 if test "$echo_libs" = "yes"; then
-      libdirs="$libdir -L$libdir"
+      libdirs="-L$libdir"
       if test -n "$lib_ssl"; then
        libdirs="$libdirs -lssl${major_version}"
       fi
```
Should I download the source and create a proper patch?

**Comment by SilvanScherrer** [comment]
this is a bug in the nss-config.in and friends. I wonder what i smoked while changing them. I will fix that asap of course

**Comment by SilvanScherrer** [comment]
New 3.47.0-2 rpm should fix it.

**Comment by dryeo** [comment]
Thanks, I'll verify once it propagates.
